name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build, Sign, and Release APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Get Version for the Release Tag
      - name: Get version from pubspec.yaml
        id: version
        run: echo "version=$(grep "version:" pubspec.yaml | cut -c10-)" >> $GITHUB_OUTPUT

      # 2. Setup Environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      # 3. Create the .env file (CRITICAL STEP FROM YOUR OLD CONFIG)
      - name: Create .env file
        run: |
          mkdir -p assets
          echo "${{ secrets.ENV_FILE }}" > assets/.env

      - name: Get packages
        run: flutter pub get

      # 5. Decode the Keystore from Secrets
      - name: Decode Keystore
        run: echo "${{ secrets.KEY_JKS }}" | base64 -d > release-keystore.jks

      # 5.1 Print Keystore Fingerprint (Debug Map Issue)
      - name: Print Keystore Fingerprint
        run: |
          keytool -list -v \
            -keystore release-keystore.jks \
            -alias release \
            -storepass "${{ secrets.KEY_PASSWORD }}"

      # 6. Build APK (Let Gradle sign it)
      - name: Build APK
        run: flutter build apk --release --split-per-abi
        env:
          KEY_PATH: ../release-keystore.jks # Path relative to android/app (gradle root)
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: release

      # 7. Clean up secrets
      - name: Cleanup Keystore
        if: always()
        run: rm -f release-keystore.jks

      # 8. Generate Date and Tag for Release
      - name: Get current date
        id: date
        run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT

      - name: Generate unique tag
        id: tag
        run: echo "tag=v${{ steps.version.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # 9. Create GitHub Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          body: "Published at ${{ steps.date.outputs.date }}"
          name: "v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}